import Head from "next/head";
import styles from "../styles/Home.module.css";
import Body from "./components/layouts/Body";
import Cat from "./components/organisms/Cat";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Cat />
        <Body />
      </main>

      {/* <Footer /> */}
    </div>
  );
}
