import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { couldStartTrivia } from "typescript";
import styles from "../styles/Home.module.css";
import { Body } from "./components/layouts/Body";
import { Footer } from "./components/layouts/Footer";
import { Header } from "./components/layouts/Header";
import { Cat } from "./components/organisms/Cat";
import { Todo } from "./components/organisms/Todo";
import { TopSearchBar } from "./components/organisms/TopSearchBar";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Cat />
        <Body />
      </main>

      {/* <Footer /> */}
    </div>
  );
}
